# Generated by Django 3.2 on 2022-04-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE content.genre_film_work DROP CONSTRAINT genre_film_work_film_work_id_65abe300_fk_film_work_id;
                ALTER TABLE content.genre_film_work DROP CONSTRAINT genre_film_work_genre_id_88fbcf0d_fk_genre_id;
                ALTER TABLE content.person_film_work DROP CONSTRAINT person_film_work_film_work_id_1724c536_fk_film_work_id;
                ALTER TABLE content.person_film_work DROP CONSTRAINT person_film_work_person_id_196d24de_fk_person_id;
            """,
            reverse_sql="""ALTER TABLE content.genre_film_work ADD CONSTRAINT genre_film_work_fk_film_work_id FOREIGN KEY (film_work_id) REFERENCES content.film_work(id) DEFERRABLE INITIALLY DEFERRED; 
                           SET CONSTRAINTS content.genre_film_work_fk_film_work_id IMMEDIATE;
                           ALTER TABLE content.genre_film_work ADD CONSTRAINT genre_film_work_fk_genre_id FOREIGN KEY (genre_id) REFERENCES content.genre(id) DEFERRABLE INITIALLY DEFERRED;
                           SET CONSTRAINTS content.genre_film_work_fk_genre_id IMMEDIATE;
                           ALTER TABLE content.person_film_work ADD CONSTRAINT person_film_work_fk_film_work_id FOREIGN KEY (film_work_id) REFERENCES content.film_work(id) DEFERRABLE INITIALLY DEFERRED;
                           SET CONSTRAINTS content.person_film_work_fk_film_work_id IMMEDIATE;
                           ALTER TABLE content.person_film_work ADD CONSTRAINT person_film_work_fk_person_id FOREIGN KEY (person_id) REFERENCES content.person(id) DEFERRABLE INITIALLY DEFERRED;
                           SET CONSTRAINTS content.person_film_work_fk_person_id IMMEDIATE;
                           """,
        )
    ]
